### ISSUE TITLE
it.skip and it.only are not functions

### ISSUE THREAD

**Issue by tchambard** [Sage/f-mocha#1]
@bjouhier 
Hi Bruno,

When using f-mocha, it is not possible to use inclusive and exclusive test with skip and only keywords on it declarations.
Do you think it would be possible to manage this need without too many changes ?

Thanks by advance
Teddy

**Comment by bjouhier** [comment]
Hi Teddy, could you post a small sample of what you want to write. I'll take a look.

**Comment by tchambard** [comment]
I did the fix and created a pull request
